package roy.ij.postofficesaathi.analytics

object AnalyticsParam {
    const val Screen = "screen"
    const val ButtonId = "button_id"
    const val Flow = "flow"
    const val LayoutType = "layout_type"
    const val CaptureSource = "capture_source"
    const val FormId = "form_id"
    const val FormCategory = "form_category"
    const val FormLanguage = "form_language"
    const val QueryTextSafe = "query_text_safe"
    const val QueryLengthBucket = "query_length_bucket"
    const val ResultCountBucket = "result_count_bucket"
    const val DurationBucket = "duration_bucket"
    const val ErrorArea = "error_area"
    const val ErrorType = "error_type"
    const val Granted = "granted"
    const val ImageCount = "image_count"
    const val FromCache = "from_cache"
    const val UsedFallback = "used_fallback"
    const val ThemeMode = "theme_mode"
    const val SchemeType = "scheme_type"
    const val TDTenure = "td_tenure"
    const val InvestmentAmountBucket = "investment_amount_bucket"
    const val TenureBucket = "tenure_bucket"
    const val HorizonYears = "horizon_years"
    const val RiskPreference = "risk_preference"
    const val AgentContactType = "agent_contact_type"
    const val AgentId = "agent_id"
    const val RatesVersion = "rates_version"
    const val PincodePrefix = "pincode_prefix"
    const val InputYear = "input_year"
    const val InputMonth = "input_month"
    const val FallbackRate = "fallback_rate"
    const val FallbackEffectiveFrom = "fallback_effective_from"
}
