package roy.ij.postofficesaathi.analytics

object AnalyticsEvent {
    const val ScreenViewed = "screen_viewed"
    const val ScreenTime = "screen_time"
    const val ButtonTapped = "button_tapped"
    const val FormSearch = "form_search"
    const val FormSearchEmpty = "form_search_empty"
    const val FormDownloadStarted = "form_download_started"
    const val FormDownloadSucceeded = "form_download_succeeded"
    const val FormDownloadFailed = "form_download_failed"
    const val FormOpened = "form_opened"
    const val FormShared = "form_shared"
    const val PdfFlowStarted = "pdf_flow_started"
    const val PdfLayoutSelected = "pdf_layout_selected"
    const val CameraPermissionResult = "camera_permission_result"
    const val CaptureStarted = "capture_started"
    const val CaptureSucceeded = "capture_succeeded"
    const val CaptureFailed = "capture_failed"
    const val GalleryImportSucceeded = "gallery_import_succeeded"
    const val GalleryImportFailed = "gallery_import_failed"
    const val CornerDetectionResult = "corner_detection_result"
    const val ImageAdjusted = "image_adjusted"
    const val PdfPreviewReset = "pdf_preview_reset"
    const val PdfCreateStarted = "pdf_create_started"
    const val PdfCreateSucceeded = "pdf_create_succeeded"
    const val PdfCreateFailed = "pdf_create_failed"
    const val PdfOpened = "pdf_opened"
    const val PdfShared = "pdf_shared"
}
