package roy.ij.postofficesaathi.ui.theme

import androidx.compose.ui.graphics.Color

val PostalRed = Color(0xFF91000A)
val PostalRedDeep = Color(0xFF6F0008)
val PostalRedBright = Color(0xFFC91D1D)
val PostalRedContainer = Color(0xFFFFE1DD)
val PostalBlue = Color(0xFF38617A)
val PostalBlueContainer = Color(0xFFE7F0F4)
val PostalAmber = Color(0xFFF0B429)
val WarmBackground = Color(0xFFFFF7F1)
val WarmSurface = Color(0xFFFFFCF8)
val WarmSurfaceContainer = Color(0xFFFFEDE5)
val WarmSurfaceHigh = Color(0xFFFFE3D6)
val GlassSurface = Color(0xEFFFFFFF)
val SoftRedTint = Color(0xFFFFDAD6)
val SoftBlueTint = Color(0xFFDCEBFF)
val PostalText = Color(0xFF171A21)
val PostalTextVariant = Color(0xFF624D48)
val PostalOutline = Color(0xFFD8B9B0)
val PostalOutlineVariant = Color(0xFFEFD4CC)

val NightBackground = Color(0xFF10131A)
val NightSurface = Color(0xFF1A1F28)
val NightSurfaceContainer = Color(0xFF222936)
val NightSurfaceHigh = Color(0xFF2C3442)
val NightText = Color(0xFFF6F7FB)
val NightTextVariant = Color(0xFFC8D0DD)
val NightOutline = Color(0xFF6D7482)
val NightOutlineVariant = Color(0xFF3B4453)
val NightRed = Color(0xFFFF8A80)
val NightBlue = Color(0xFF7DB7FF)
val NightAmber = Color(0xFFFFD166)
